// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/openwrt/internal/dagger"

	"dagger.io/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject = querybuilder.GraphQLMarshaller

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Openwrt) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Version           string
		Target            string
		UCIPackages       []string
		UCIDefaultScripts []*dagger.File
	}
	concrete.Version = r.Version
	concrete.Target = r.Target
	concrete.UCIPackages = r.UCIPackages
	concrete.UCIDefaultScripts = r.UCIDefaultScripts
	return json.Marshal(&concrete)
}

func (r *Openwrt) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Version           string
		Target            string
		UCIPackages       []string
		UCIDefaultScripts []*dagger.File
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Version = concrete.Version
	r.Target = concrete.Target
	r.UCIPackages = concrete.UCIPackages
	r.UCIDefaultScripts = concrete.UCIDefaultScripts
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Openwrt":
		switch fnName {
		case "Build":
			var parent Openwrt
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var profile string
			if inputArgs["profile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["profile"]), &profile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg profile", err))
				}
			}
			var packages []string
			if inputArgs["packages"] != nil {
				err = json.Unmarshal([]byte(inputArgs["packages"]), &packages)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg packages", err))
				}
			}
			var disabledServices []string
			if inputArgs["disabledServices"] != nil {
				err = json.Unmarshal([]byte(inputArgs["disabledServices"]), &disabledServices)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg disabledServices", err))
				}
			}
			var rootSizeMb string
			if inputArgs["rootSizeMB"] != nil {
				err = json.Unmarshal([]byte(inputArgs["rootSizeMB"]), &rootSizeMb)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg rootSizeMB", err))
				}
			}
			return (*Openwrt).Build(&parent, ctx, profile, packages, disabledServices, rootSizeMb), nil
		case "Diff":
			var parent Openwrt
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var newPackages *dagger.File
			if inputArgs["newPackages"] != nil {
				err = json.Unmarshal([]byte(inputArgs["newPackages"]), &newPackages)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg newPackages", err))
				}
			}
			var oldPackages *dagger.File
			if inputArgs["oldPackages"] != nil {
				err = json.Unmarshal([]byte(inputArgs["oldPackages"]), &oldPackages)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg oldPackages", err))
				}
			}
			return (*Openwrt).Diff(&parent, ctx, newPackages, oldPackages)
		case "ImageBuilder":
			var parent Openwrt
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Openwrt).ImageBuilder(&parent), nil
		case "Manifest":
			var parent Openwrt
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var profile string
			if inputArgs["profile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["profile"]), &profile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg profile", err))
				}
			}
			var packages []string
			if inputArgs["packages"] != nil {
				err = json.Unmarshal([]byte(inputArgs["packages"]), &packages)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg packages", err))
				}
			}
			return (*Openwrt).Manifest(&parent, ctx, profile, packages)
		case "Profiles":
			var parent Openwrt
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Openwrt).Profiles(&parent, ctx)
		case "WithNonPrivilegedUser":
			var parent Openwrt
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var pubkey *dagger.File
			if inputArgs["pubkey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pubkey"]), &pubkey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pubkey", err))
				}
			}
			var tmpl *dagger.File
			if inputArgs["tmpl"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tmpl"]), &tmpl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tmpl", err))
				}
			}
			return (*Openwrt).WithNonPrivilegedUser(&parent, ctx, name, pubkey, tmpl)
		case "":
			var parent Openwrt
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			var target string
			if inputArgs["target"] != nil {
				err = json.Unmarshal([]byte(inputArgs["target"]), &target)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg target", err))
				}
			}
			return New(version, target), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
