// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `RemoteCacheBackendID` scalar type represents an identifier for an object of type RemoteCacheBackend.
type RemoteCacheBackendID string // remote-cache (../../../../remote-cache/main.go:21:6)

// The `RemoteCacheID` scalar type represents an identifier for an object of type RemoteCache.
type RemoteCacheID string // remote-cache (../../../../remote-cache/main.go:17:6)

// The `RemoteCacheVolumeMountID` scalar type represents an identifier for an object of type RemoteCacheVolumeMount.
type RemoteCacheVolumeMountID string // remote-cache (../../../../remote-cache/main.go:27:6)

// Retrieve the binding value, as type RemoteCache
func (r *Binding) AsRemoteCache() *RemoteCache { // remote-cache (../../../../remote-cache/main.go:17:6)
	q := r.query.Select("asRemoteCache")

	return &RemoteCache{
		query: q,
	}
}

// Retrieve the binding value, as type RemoteCacheBackend
func (r *Binding) AsRemoteCacheBackend() *RemoteCacheBackend { // remote-cache (../../../../remote-cache/main.go:21:6)
	q := r.query.Select("asRemoteCacheBackend")

	return &RemoteCacheBackend{
		query: q,
	}
}

// Retrieve the binding value, as type RemoteCacheVolumeMount
func (r *Binding) AsRemoteCacheVolumeMount() *RemoteCacheVolumeMount { // remote-cache (../../../../remote-cache/main.go:27:6)
	q := r.query.Select("asRemoteCacheVolumeMount")

	return &RemoteCacheVolumeMount{
		query: q,
	}
}

// Create or update a binding of type RemoteCacheBackend in the environment
func (r *Env) WithRemoteCacheBackendInput(name string, value *RemoteCacheBackend, description string) *Env { // remote-cache (../../../../remote-cache/main.go:21:6)
	assertNotNil("value", value)
	q := r.query.Select("withRemoteCacheBackendInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired RemoteCacheBackend output to be assigned in the environment
func (r *Env) WithRemoteCacheBackendOutput(name string, description string) *Env { // remote-cache (../../../../remote-cache/main.go:21:6)
	q := r.query.Select("withRemoteCacheBackendOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type RemoteCache in the environment
func (r *Env) WithRemoteCacheInput(name string, value *RemoteCache, description string) *Env { // remote-cache (../../../../remote-cache/main.go:17:6)
	assertNotNil("value", value)
	q := r.query.Select("withRemoteCacheInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired RemoteCache output to be assigned in the environment
func (r *Env) WithRemoteCacheOutput(name string, description string) *Env { // remote-cache (../../../../remote-cache/main.go:17:6)
	q := r.query.Select("withRemoteCacheOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type RemoteCacheVolumeMount in the environment
func (r *Env) WithRemoteCacheVolumeMountInput(name string, value *RemoteCacheVolumeMount, description string) *Env { // remote-cache (../../../../remote-cache/main.go:27:6)
	assertNotNil("value", value)
	q := r.query.Select("withRemoteCacheVolumeMountInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired RemoteCacheVolumeMount output to be assigned in the environment
func (r *Env) WithRemoteCacheVolumeMountOutput(name string, description string) *Env { // remote-cache (../../../../remote-cache/main.go:27:6)
	q := r.query.Select("withRemoteCacheVolumeMountOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Load a RemoteCache from its ID.
func (r *Query) LoadRemoteCacheFromID(id RemoteCacheID) *RemoteCache { // remote-cache (../../../../remote-cache/main.go:17:6)
	q := r.query.Select("loadRemoteCacheFromID")
	q = q.Arg("id", id)

	return &RemoteCache{
		query: q,
	}
}

// Load a RemoteCacheVolumeMount from its ID.
func (r *Query) LoadRemoteCacheVolumeMountFromID(id RemoteCacheVolumeMountID) *RemoteCacheVolumeMount { // remote-cache (../../../../remote-cache/main.go:27:6)
	q := r.query.Select("loadRemoteCacheVolumeMountFromID")
	q = q.Arg("id", id)

	return &RemoteCacheVolumeMount{
		query: q,
	}
}

func (r *Query) RemoteCache(backend *RemoteCacheBackend) *RemoteCache { // remote-cache (../../../../remote-cache/main.go:43:1)
	assertNotNil("backend", backend)
	q := r.query.Select("remoteCache")
	q = q.Arg("backend", backend)

	return &RemoteCache{
		query: q,
	}
}

type RemoteCache struct { // remote-cache (../../../../remote-cache/main.go:17:6)
	query *querybuilder.Selection

	id *RemoteCacheID
}

func (r *RemoteCache) WithGraphQLQuery(q *querybuilder.Selection) *RemoteCache {
	return &RemoteCache{
		query: q,
	}
}

func (r *RemoteCache) Export(ctr *Container) *Container { // remote-cache (../../../../remote-cache/main.go:165:1)
	assertNotNil("ctr", ctr)
	q := r.query.Select("export")
	q = q.Arg("ctr", ctr)

	return &Container{
		query: q,
	}
}

// A unique identifier for this RemoteCache.
func (r *RemoteCache) ID(ctx context.Context) (RemoteCacheID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response RemoteCacheID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *RemoteCache) XXX_GraphQLType() string {
	return "RemoteCache"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *RemoteCache) XXX_GraphQLIDType() string {
	return "RemoteCacheID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *RemoteCache) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *RemoteCache) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *RemoteCache) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadRemoteCacheFromID(RemoteCacheID(id))
	return nil
}

// RemoteCacheMountOpts contains options for RemoteCache.Mount
type RemoteCacheMountOpts struct {
	//
	// A user:group to set for the mounted cache directory.
	//
	Owner string // remote-cache (../../../../remote-cache/main.go:56:2)
	//
	// Replace "${VAR}" or "$VAR" in the value of path according to the current environment variables defined in the container (e.g. "/$VAR/foo").
	//
	Expand bool // remote-cache (../../../../remote-cache/main.go:59:2)

	PlatformAware bool // remote-cache (../../../../remote-cache/main.go:61:2)

	Force bool // remote-cache (../../../../remote-cache/main.go:63:2)
}

func (r *RemoteCache) Mount(path string, key string, opts ...RemoteCacheMountOpts) *RemoteCacheVolumeMount { // remote-cache (../../../../remote-cache/main.go:49:1)
	q := r.query.Select("mount")
	for i := len(opts) - 1; i >= 0; i-- {
		// `owner` optional argument
		if !querybuilder.IsZeroValue(opts[i].Owner) {
			q = q.Arg("owner", opts[i].Owner)
		}
		// `expand` optional argument
		if !querybuilder.IsZeroValue(opts[i].Expand) {
			q = q.Arg("expand", opts[i].Expand)
		}
		// `platformAware` optional argument
		if !querybuilder.IsZeroValue(opts[i].PlatformAware) {
			q = q.Arg("platformAware", opts[i].PlatformAware)
		}
		// `force` optional argument
		if !querybuilder.IsZeroValue(opts[i].Force) {
			q = q.Arg("force", opts[i].Force)
		}
	}
	q = q.Arg("path", path)
	q = q.Arg("key", key)

	return &RemoteCacheVolumeMount{
		query: q,
	}
}

type RemoteCacheBackend struct { // remote-cache (../../../../remote-cache/main.go:21:6)
	query *querybuilder.Selection

	export *Void
	id     *RemoteCacheBackendID
}

func (r *RemoteCacheBackend) WithGraphQLQuery(q *querybuilder.Selection) *RemoteCacheBackend {
	return &RemoteCacheBackend{
		query: q,
	}
}

func (r *RemoteCacheBackend) Export(ctx context.Context, key string, dir *Directory) error { // remote-cache (../../../../remote-cache/main.go:24:8)
	assertNotNil("dir", dir)
	if r.export != nil {
		return nil
	}
	q := r.query.Select("export")
	q = q.Arg("key", key)
	q = q.Arg("dir", dir)

	return q.Execute(ctx)
}

// A unique identifier for this RemoteCacheBackend.
func (r *RemoteCacheBackend) ID(ctx context.Context) (RemoteCacheBackendID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response RemoteCacheBackendID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *RemoteCacheBackend) XXX_GraphQLType() string {
	return "RemoteCacheBackend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *RemoteCacheBackend) XXX_GraphQLIDType() string {
	return "RemoteCacheBackendID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *RemoteCacheBackend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *RemoteCacheBackend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *RemoteCacheBackend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadRemoteCacheBackendFromID(RemoteCacheBackendID(id))
	return nil
}

func (r *RemoteCacheBackend) Import(key string) *Directory { // remote-cache (../../../../remote-cache/main.go:23:8)
	q := r.query.Select("import")
	q = q.Arg("key", key)

	return &Directory{
		query: q,
	}
}

type RemoteCacheVolumeMount struct { // remote-cache (../../../../remote-cache/main.go:27:6)
	query *querybuilder.Selection

	id *RemoteCacheVolumeMountID
}

func (r *RemoteCacheVolumeMount) WithGraphQLQuery(q *querybuilder.Selection) *RemoteCacheVolumeMount {
	return &RemoteCacheVolumeMount{
		query: q,
	}
}

func (r *RemoteCacheVolumeMount) AsCacheVolume(ctr *Container) *Container { // remote-cache (../../../../remote-cache/main.go:88:1)
	assertNotNil("ctr", ctr)
	q := r.query.Select("asCacheVolume")
	q = q.Arg("ctr", ctr)

	return &Container{
		query: q,
	}
}

func (r *RemoteCacheVolumeMount) AsDirectory(ctr *Container) *Container { // remote-cache (../../../../remote-cache/main.go:137:1)
	assertNotNil("ctr", ctr)
	q := r.query.Select("asDirectory")
	q = q.Arg("ctr", ctr)

	return &Container{
		query: q,
	}
}

// A unique identifier for this RemoteCacheVolumeMount.
func (r *RemoteCacheVolumeMount) ID(ctx context.Context) (RemoteCacheVolumeMountID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response RemoteCacheVolumeMountID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *RemoteCacheVolumeMount) XXX_GraphQLType() string {
	return "RemoteCacheVolumeMount"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *RemoteCacheVolumeMount) XXX_GraphQLIDType() string {
	return "RemoteCacheVolumeMountID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *RemoteCacheVolumeMount) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *RemoteCacheVolumeMount) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *RemoteCacheVolumeMount) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadRemoteCacheVolumeMountFromID(RemoteCacheVolumeMountID(id))
	return nil
}
