// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `RemoteBackendID` scalar type represents an identifier for an object of type RemoteBackend.
type RemoteBackendID string // remote-backend (../../../../remote-backend/main.go:3:6)

// The `RemoteBackendLocalID` scalar type represents an identifier for an object of type RemoteBackendLocal.
type RemoteBackendLocalID string // remote-backend (../../../../remote-backend/local.go:9:6)

// The `RemoteBackendRegistryID` scalar type represents an identifier for an object of type RemoteBackendRegistry.
type RemoteBackendRegistryID string // remote-backend (../../../../remote-backend/registry.go:11:6)

// Retrieve the binding value, as type RemoteBackend
func (r *Binding) AsRemoteBackend() *RemoteBackend { // remote-backend (../../../../remote-backend/main.go:3:6)
	q := r.query.Select("asRemoteBackend")

	return &RemoteBackend{
		query: q,
	}
}

// Retrieve the binding value, as type RemoteBackendLocal
func (r *Binding) AsRemoteBackendLocal() *RemoteBackendLocal { // remote-backend (../../../../remote-backend/local.go:9:6)
	q := r.query.Select("asRemoteBackendLocal")

	return &RemoteBackendLocal{
		query: q,
	}
}

// Retrieve the binding value, as type RemoteBackendRegistry
func (r *Binding) AsRemoteBackendRegistry() *RemoteBackendRegistry { // remote-backend (../../../../remote-backend/registry.go:11:6)
	q := r.query.Select("asRemoteBackendRegistry")

	return &RemoteBackendRegistry{
		query: q,
	}
}

// Create or update a binding of type RemoteBackend in the environment
func (r *Env) WithRemoteBackendInput(name string, value *RemoteBackend, description string) *Env { // remote-backend (../../../../remote-backend/main.go:3:6)
	assertNotNil("value", value)
	q := r.query.Select("withRemoteBackendInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type RemoteBackendLocal in the environment
func (r *Env) WithRemoteBackendLocalInput(name string, value *RemoteBackendLocal, description string) *Env { // remote-backend (../../../../remote-backend/local.go:9:6)
	assertNotNil("value", value)
	q := r.query.Select("withRemoteBackendLocalInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired RemoteBackendLocal output to be assigned in the environment
func (r *Env) WithRemoteBackendLocalOutput(name string, description string) *Env { // remote-backend (../../../../remote-backend/local.go:9:6)
	q := r.query.Select("withRemoteBackendLocalOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired RemoteBackend output to be assigned in the environment
func (r *Env) WithRemoteBackendOutput(name string, description string) *Env { // remote-backend (../../../../remote-backend/main.go:3:6)
	q := r.query.Select("withRemoteBackendOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type RemoteBackendRegistry in the environment
func (r *Env) WithRemoteBackendRegistryInput(name string, value *RemoteBackendRegistry, description string) *Env { // remote-backend (../../../../remote-backend/registry.go:11:6)
	assertNotNil("value", value)
	q := r.query.Select("withRemoteBackendRegistryInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired RemoteBackendRegistry output to be assigned in the environment
func (r *Env) WithRemoteBackendRegistryOutput(name string, description string) *Env { // remote-backend (../../../../remote-backend/registry.go:11:6)
	q := r.query.Select("withRemoteBackendRegistryOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Load a RemoteBackend from its ID.
func (r *Query) LoadRemoteBackendFromID(id RemoteBackendID) *RemoteBackend { // remote-backend (../../../../remote-backend/main.go:3:6)
	q := r.query.Select("loadRemoteBackendFromID")
	q = q.Arg("id", id)

	return &RemoteBackend{
		query: q,
	}
}

// Load a RemoteBackendLocal from its ID.
func (r *Query) LoadRemoteBackendLocalFromID(id RemoteBackendLocalID) *RemoteBackendLocal { // remote-backend (../../../../remote-backend/local.go:9:6)
	q := r.query.Select("loadRemoteBackendLocalFromID")
	q = q.Arg("id", id)

	return &RemoteBackendLocal{
		query: q,
	}
}

// Load a RemoteBackendRegistry from its ID.
func (r *Query) LoadRemoteBackendRegistryFromID(id RemoteBackendRegistryID) *RemoteBackendRegistry { // remote-backend (../../../../remote-backend/registry.go:11:6)
	q := r.query.Select("loadRemoteBackendRegistryFromID")
	q = q.Arg("id", id)

	return &RemoteBackendRegistry{
		query: q,
	}
}

func (r *Query) RemoteBackend() *RemoteBackend { // remote-backend (../../../../remote-backend/main.go:3:6)
	q := r.query.Select("remoteBackend")

	return &RemoteBackend{
		query: q,
	}
}

type RemoteBackend struct { // remote-backend (../../../../remote-backend/main.go:3:6)
	query *querybuilder.Selection

	id *RemoteBackendID
}

func (r *RemoteBackend) WithGraphQLQuery(q *querybuilder.Selection) *RemoteBackend {
	return &RemoteBackend{
		query: q,
	}
}

// A unique identifier for this RemoteBackend.
func (r *RemoteBackend) ID(ctx context.Context) (RemoteBackendID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response RemoteBackendID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *RemoteBackend) XXX_GraphQLType() string {
	return "RemoteBackend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *RemoteBackend) XXX_GraphQLIDType() string {
	return "RemoteBackendID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *RemoteBackend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *RemoteBackend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *RemoteBackend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadRemoteBackendFromID(RemoteBackendID(id))
	return nil
}

func (r *RemoteBackend) Local() *RemoteBackendLocal { // remote-backend (../../../../remote-backend/local.go:11:1)
	q := r.query.Select("local")

	return &RemoteBackendLocal{
		query: q,
	}
}

// RemoteBackendRegistryOpts contains options for RemoteBackend.Registry
type RemoteBackendRegistryOpts struct {
	//
	// Image registry username
	//
	Username string // remote-backend (../../../../remote-backend/registry.go:25:2)
	//
	// Image registry password
	//
	Password *Secret // remote-backend (../../../../remote-backend/registry.go:28:2)
}

func (r *RemoteBackend) Registry(registry string, repo string, opts ...RemoteBackendRegistryOpts) *RemoteBackendRegistry { // remote-backend (../../../../remote-backend/registry.go:18:1)
	q := r.query.Select("registry")
	for i := len(opts) - 1; i >= 0; i-- {
		// `username` optional argument
		if !querybuilder.IsZeroValue(opts[i].Username) {
			q = q.Arg("username", opts[i].Username)
		}
		// `password` optional argument
		if !querybuilder.IsZeroValue(opts[i].Password) {
			q = q.Arg("password", opts[i].Password)
		}
	}
	q = q.Arg("registry", registry)
	q = q.Arg("repo", repo)

	return &RemoteBackendRegistry{
		query: q,
	}
}

type RemoteBackendLocal struct { // remote-backend (../../../../remote-backend/local.go:9:6)
	query *querybuilder.Selection

	export *Void
	id     *RemoteBackendLocalID
}

func (r *RemoteBackendLocal) WithGraphQLQuery(q *querybuilder.Selection) *RemoteBackendLocal {
	return &RemoteBackendLocal{
		query: q,
	}
}

// Converts this RemoteBackendLocal to a RemoteCacheBackend.
func (r *RemoteBackendLocal) AsRemoteCacheBackend() *RemoteCacheBackend {
	q := r.query.Select("asRemoteCacheBackend")

	return &RemoteCacheBackend{
		query: q,
	}
}

func (r *RemoteBackendLocal) Export(ctx context.Context, key string, dir *Directory) error { // remote-backend (../../../../remote-backend/local.go:19:1)
	assertNotNil("dir", dir)
	if r.export != nil {
		return nil
	}
	q := r.query.Select("export")
	q = q.Arg("key", key)
	q = q.Arg("dir", dir)

	return q.Execute(ctx)
}

// A unique identifier for this RemoteBackendLocal.
func (r *RemoteBackendLocal) ID(ctx context.Context) (RemoteBackendLocalID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response RemoteBackendLocalID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *RemoteBackendLocal) XXX_GraphQLType() string {
	return "RemoteBackendLocal"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *RemoteBackendLocal) XXX_GraphQLIDType() string {
	return "RemoteBackendLocalID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *RemoteBackendLocal) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *RemoteBackendLocal) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *RemoteBackendLocal) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadRemoteBackendLocalFromID(RemoteBackendLocalID(id))
	return nil
}

func (r *RemoteBackendLocal) Import(key string) *Directory { // remote-backend (../../../../remote-backend/local.go:15:1)
	q := r.query.Select("import")
	q = q.Arg("key", key)

	return &Directory{
		query: q,
	}
}

// OCI registry backend
type RemoteBackendRegistry struct { // remote-backend (../../../../remote-backend/registry.go:11:6)
	query *querybuilder.Selection

	export *Void
	id     *RemoteBackendRegistryID
}

func (r *RemoteBackendRegistry) WithGraphQLQuery(q *querybuilder.Selection) *RemoteBackendRegistry {
	return &RemoteBackendRegistry{
		query: q,
	}
}

// Converts this RemoteBackendRegistry to a RemoteCacheBackend.
func (r *RemoteBackendRegistry) AsRemoteCacheBackend() *RemoteCacheBackend {
	q := r.query.Select("asRemoteCacheBackend")

	return &RemoteCacheBackend{
		query: q,
	}
}

func (r *RemoteBackendRegistry) Export(ctx context.Context, key string, dir *Directory) error { // remote-backend (../../../../remote-backend/registry.go:54:1)
	assertNotNil("dir", dir)
	if r.export != nil {
		return nil
	}
	q := r.query.Select("export")
	q = q.Arg("key", key)
	q = q.Arg("dir", dir)

	return q.Execute(ctx)
}

// A unique identifier for this RemoteBackendRegistry.
func (r *RemoteBackendRegistry) ID(ctx context.Context) (RemoteBackendRegistryID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response RemoteBackendRegistryID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *RemoteBackendRegistry) XXX_GraphQLType() string {
	return "RemoteBackendRegistry"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *RemoteBackendRegistry) XXX_GraphQLIDType() string {
	return "RemoteBackendRegistryID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *RemoteBackendRegistry) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *RemoteBackendRegistry) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *RemoteBackendRegistry) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadRemoteBackendRegistryFromID(RemoteBackendRegistryID(id))
	return nil
}

func (r *RemoteBackendRegistry) Import(key string) *Directory { // remote-backend (../../../../remote-backend/registry.go:38:1)
	q := r.query.Select("import")
	q = q.Arg("key", key)

	return &Directory{
		query: q,
	}
}
