// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/remote-cache/internal/dagger"

	"dagger.io/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject = querybuilder.GraphQLMarshaller

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r RemoteCache) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Backend any
	}
	concrete.Backend = r.Backend
	return json.Marshal(&concrete)
}

func (r *RemoteCache) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Backend *backendImpl
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Backend = concrete.Backend.toIface()
	return nil
}

func (r VolumeMount) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Cache  *RemoteCache
		Meta   MountMetadata
		Volume *dagger.CacheVolume
	}
	concrete.Cache = r.Cache
	concrete.Meta = r.Meta
	concrete.Volume = r.Volume
	return json.Marshal(&concrete)
}

func (r *VolumeMount) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Cache  *RemoteCache
		Meta   MountMetadata
		Volume *dagger.CacheVolume
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Cache = concrete.Cache
	r.Meta = concrete.Meta
	r.Volume = concrete.Volume
	return nil
}

type backendImpl struct {
	query *querybuilder.Selection
	id    *BackendID
}

type BackendID string

func LoadBackendFromID(r *dagger.Client, id BackendID) Backend {
	q := querybuilder.Query().Client(r.GraphQLClient())
	q = q.Select("loadRemoteCacheBackendFromID")
	q = q.Arg("id", id)
	return &backendImpl{query: q}
}

func (r *backendImpl) WithGraphQLQuery(q *querybuilder.Selection) Backend {
	return &backendImpl{query: q}
}

func (r *backendImpl) XXX_GraphQLType() string {
	return "Backend"
}

func (r *backendImpl) XXX_GraphQLIDType() string {
	return "BackendID"
}

func (r *backendImpl) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *backendImpl) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("\"\""), nil
	}
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *backendImpl) UnmarshalJSON(bs []byte) error {
	var id BackendID
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *LoadBackendFromID(dag, id).(*backendImpl)
	return nil
}

func (r *backendImpl) toIface() Backend {
	if r == nil {
		return nil
	}
	return r
}

func (r *backendImpl) ID(ctx context.Context) (BackendID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")
	var response BackendID
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *backendImpl) Export(ctx context.Context, key string, dir *dagger.Directory) error {
	q := r.query.Select("export")
	q = q.Arg("key", key)

	q = q.Arg("dir", dir)

	var response dagger.Void
	q = q.Bind(&response)
	return q.Execute(ctx)
}

func (r *backendImpl) Import(ctx context.Context, key string) *dagger.Directory {
	q := r.query.Select("import")
	q = q.Arg("key", key)

	return (&dagger.Directory{}).WithGraphQLQuery(q)
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "RemoteCache":
		switch fnName {
		case "Export":
			var parent RemoteCache
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ctr *dagger.Container
			if inputArgs["ctr"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ctr"]), &ctr)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ctr", err))
				}
			}
			return (*RemoteCache).Export(&parent, ctx, ctr)
		case "Mount":
			var parent RemoteCache
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			var key string
			if inputArgs["key"] != nil {
				err = json.Unmarshal([]byte(inputArgs["key"]), &key)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg key", err))
				}
			}
			var owner string
			if inputArgs["owner"] != nil {
				err = json.Unmarshal([]byte(inputArgs["owner"]), &owner)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg owner", err))
				}
			}
			var expand bool
			if inputArgs["expand"] != nil {
				err = json.Unmarshal([]byte(inputArgs["expand"]), &expand)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg expand", err))
				}
			}
			var platformAware bool
			if inputArgs["platformAware"] != nil {
				err = json.Unmarshal([]byte(inputArgs["platformAware"]), &platformAware)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg platformAware", err))
				}
			}
			var force bool
			if inputArgs["force"] != nil {
				err = json.Unmarshal([]byte(inputArgs["force"]), &force)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg force", err))
				}
			}
			return (*RemoteCache).Mount(&parent, path, key, owner, expand, platformAware, force), nil
		case "":
			var parent RemoteCache
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var backend *backendImpl
			if inputArgs["backend"] != nil {
				err = json.Unmarshal([]byte(inputArgs["backend"]), &backend)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg backend", err))
				}
			}
			return New(backend.toIface()), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "VolumeMount":
		switch fnName {
		case "AsCacheVolume":
			var parent VolumeMount
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ctr *dagger.Container
			if inputArgs["ctr"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ctr"]), &ctr)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ctr", err))
				}
			}
			return (*VolumeMount).AsCacheVolume(&parent, ctx, ctr)
		case "AsDirectory":
			var parent VolumeMount
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ctr *dagger.Container
			if inputArgs["ctr"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ctr"]), &ctr)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ctr", err))
				}
			}
			return (*VolumeMount).AsDirectory(&parent, ctx, ctr)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
